# Generated by Django 3.0.2 on 2020-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
