# Generated by Django 3.0.2 on 2020-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200124_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldPrice',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
    ]
