# Generated by Django 3.0.2 on 2020-01-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailedImage',
            field=models.TextField(db_index=True, default='none'),
        ),
    ]
