# Generated by Django 3.0.2 on 2020-02-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailedImage',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
