# Generated by Django 3.0.2 on 2020-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200212_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
    ]
